imports:
    - { resource: services/criterion_handlers.yml }
    - { resource: services/url_checker.yml }

parameters:
    ezpublish.api.service.url_inner.class: 'EzSystems\EzPlatformLinkManager\Core\Repository\URLService'
    ezpublish.api.service.url.signalslot.class: 'EzSystems\EzPlatformLinkManager\Core\SignalSlot\URLService'
    ezpublish.persistence.legacy.gateway.url.exception_conversion.class: 'EzSystems\EzPlatformLinkManager\Core\Persistence\Legacy\URL\Gateway\ExceptionConversion'
    ezpublish.persistence.legacy.url.gateway.inner.class: 'EzSystems\EzPlatformLinkManager\Core\Persistence\Legacy\URL\Gateway\DoctrineDatabase'
    ezpublish.persistence.legacy.url.mapper.class: 'EzSystems\EzPlatformLinkManager\Core\Persistence\Legacy\URL\Mapper'
    ezpublish.spi.persistence.cache.url.handler.class: 'EzSystems\EzPlatformLinkManager\Core\Persistence\Cache\URLHandler'
    ezpublish.spi.persistence.legacy.url.handler.class: 'EzSystems\EzPlatformLinkManager\Core\Persistence\Legacy\URL\Handler'
    ezpublish.spi.persistence.legacy.url.criterion_converter.class: 'EzSystems\EzPlatformLinkManager\Core\Persistence\Legacy\URL\Query\CriteriaConverter'
    ezsystems.platformui.controller.link_management.class: 'EzSystems\EzPlatformLinkManagerBundle\Controller\LinkManagerController'
    ezsystems.form.type.url_list.class: 'EzSystems\EzPlatformLinkManagerBundle\Form\Type\URL\URLListType'
    ezsystems.form.type.url_edit.class: 'EzSystems\EzPlatformLinkManagerBundle\Form\Type\URL\URLEditType'
    ezplatform.link_manager.validator.unique_url.class: 'EzSystems\EzPlatformLinkManagerBundle\Validator\Constraints\UniqueURLValidator'

services:
    ezpublish.api.service.url:
        alias: 'ezpublish.api.service.url.signalslot'

    ezpublish.api.service.url.signalslot:
        class: '%ezpublish.api.service.url.signalslot.class%'
        arguments:
            - '@ezpublish.api.service.url_inner'
            - '@ezpublish.signalslot.signal_dispatcher_transaction_wrapper'

    ezpublish.api.service.url_inner:
        class: '%ezpublish.api.service.url_inner.class%'
        arguments:
            - '@ezpublish.api.repository'
            - '@ezpublish.spi.persistence.cache.url.handler'
        lazy: true

    ezpublish.persistence.legacy.gateway.url.exception_conversion:
        class: '%ezpublish.persistence.legacy.gateway.url.exception_conversion.class%'
        arguments:
            - '@ezpublish.persistence.legacy.url.gateway.inner'

    ezpublish.persistence.legacy.url.gateway.inner:
        class: '%ezpublish.persistence.legacy.url.gateway.inner.class%'
        arguments:
            - '@ezpublish.api.storage_engine.legacy.dbhandler'
            - '@ezpublish.spi.persistence.legacy.url.criterion_converter'

    ezpublish.persistence.legacy.url.gateway:
        alias: 'ezpublish.persistence.legacy.gateway.url.exception_conversion'

    ezpublish.persistence.legacy.url.mapper:
        class: '%ezpublish.persistence.legacy.url.mapper.class%'

    ezpublish.spi.persistence.legacy.url.criterion_converter:
        class: '%ezpublish.spi.persistence.legacy.url.criterion_converter.class%'

    ezpublish.spi.persistence.cache.url.handler:
        class: '%ezpublish.spi.persistence.cache.url.handler.class%'
        arguments:
            - '@ezpublish.cache_pool.spi.cache.decorator'
            - '@ezpublish.spi.persistence.legacy.url.handler'
            - '@ezpublish.spi.persistence.cache.persistenceLogger'

    ezpublish.spi.persistence.legacy.url.handler:
        class: '%ezpublish.spi.persistence.legacy.url.handler.class%'
        arguments:
            - '@ezpublish.persistence.legacy.url.gateway'
            - '@ezpublish.persistence.legacy.url.mapper'
        lazy: true

    ezsystems.platformui.controller.link_management:
        class: '%ezsystems.platformui.controller.link_management.class%'
        arguments:
            - '@ezpublish.api.service.url'
        parent: 'ezsystems.platformui.controller.base'

    ezsystems.form.type.url_list:
        class: '%ezsystems.form.type.url_list.class%'
        arguments:
            - '@translator'
        tags:
            - { name: 'form.type', alias: 'ezplatformlinkmanager_url_list' }

    ezsystems.form.type.url_edit:
        class: '%ezsystems.form.type.url_edit.class%'
        tags:
            - { name: 'form.type', alias: 'ezplatformlinkmanager_url_edit' }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    ezplatform.link_manager.validator.unique_url:
        class: '%ezplatform.link_manager.validator.unique_url.class%'
        arguments:
            - '@ezpublish.api.service.url'
        tags:
            - { name: 'validator.constraint_validator', alias: 'ezplatform.link_manager.validator.unique_url' }
