EzSystems\EzPlatformLinkManagerBundle\Form\Data\URLUpdateData:
    constraints:
        - EzSystems\EzPlatformLinkManagerBundle\Validator\Constraints\UniqueURL: ~
    properties:
        url:
            - NotBlank: ~
