parameters:
    ezpublish.url_checker.class: EzSystems\EzPlatformLinkManager\URLChecker\URLChecker
    ezpublish.url_checker.handler_registry.class: EzSystems\EzPlatformLinkManager\URLChecker\URLHandlerRegistry
    ezpublish.url_checker.handler.http.class: EzSystems\EzPlatformLinkManager\URLChecker\Handler\HTTPHandler
    ezpublish.url_checker.handler.mailto.class: EzSystems\EzPlatformLinkManager\URLChecker\Handler\MailToHandler

services:
    ezpublish.url_checker:
        class: '%ezpublish.url_checker.class%'
        arguments:
            - '@ezpublish.api.repository'
            - '@ezpublish.api.service.url_inner'
            - '@ezpublish.url_checker.handler_registry'
        calls:
            - ['setLogger', ['@?logger']]
        lazy: true

    ezpublish.url_checker.handler_registry:
        class: '%ezpublish.url_checker.handler_registry.class%'

    ezpublish.url_checker.handler.http:
        class: '%ezpublish.url_checker.handler.http.class%'
        calls:
            - ['setLogger', ['@?logger']]
        tags:
            - { name: url_checker, scheme: http }

    ezpublish.url_checker.handler.https:
        class: '%ezpublish.url_checker.handler.http.class%'
        calls:
            - ['setLogger', ['@?logger']]
        tags:
            - { name: url_checker, scheme: https }

    ezpublish.url_checker.handler.mailto:
        class: '%ezpublish.url_checker.handler.mailto.class%'
        tags:
            - { name: url_checker, scheme: mailto }
